const path = require('node:path');

const camelCase = require('lodash/camelCase');
const upperFirst = require('lodash/upperFirst');

/**
 * @typedef {import('@svgr/core').Config & Partial<{
 *   ext: string;
 *   filenameCase: string;
 *   ignoreExisting: boolean;
 *   indexTemplate: (paths: Array<{
 *     path: string;
 *     originalPath: string;
 *   }>) => string;
 *   outDir: string;
 *   silent: boolean;
 *   stdin: boolean;
 *   stdinFilepath: string;
 * }>} SVGRConfig
 */

const emptyLine = '\n\n';

const autoGenerationMessage = /** @type {const} */ (
  `/* THIS FILE WAS AUTO-GENERATED BY A SCRIPT, THEREFORE PLEASE DO NOT EDIT IT MANUALLY. */${emptyLine}`
);

/** @type {SVGRConfig} */
const config = {
  filenameCase: 'kebab',
  indexTemplate: (paths) => `
    ${autoGenerationMessage}

    ${paths
      .map(({ path: filePath }) => {
        const fileBasename = path.basename(filePath, path.extname(filePath)).trim();
        const pascalCaseFileBasename = upperFirst(camelCase(fileBasename));

        const isIcon = filePath.includes('icons');

        return `
          export { default as ${pascalCaseFileBasename}${isIcon ? 'Icon' : ''} } from './${fileBasename}';
          export { default as urlTo${pascalCaseFileBasename}${isIcon ? 'Icon' : ''} } from '../${fileBasename}.svg';
        `;
      })
      .join('\n')}
  `,
  ref: true,
  svgoConfig: {
    plugins: [
      {
        name: 'preset-default',
        params: {
          overrides: {
            removeViewBox: false,
          },
        },
      },
    ],
  },
  template: ({ componentName, props, jsx }, { tpl, options }) => {
    /** The passed component name without its "Svg" prefix, and with "Icon" as its suffix. */
    const editedComponentName = `${componentName.trim().substring(3)}Icon`;
    const displayName = editedComponentName;
    const { filePath } = /** @type {typeof options.state & { filePath: string }} */ (options.state);

    const linkToOriginalSvgFile = '/** Original SVG file location: ' + filePath.split(path.sep).join('/') + ' */\n';

    return tpl`
      ${autoGenerationMessage}

      import { forwardRef, type SVGProps, type Ref } from 'react';

      ${emptyLine}

      type SVGRProps = Partial<{
        title: string;
        titleId: string;
      }>;

      ${emptyLine}

      ${linkToOriginalSvgFile}

      const ${editedComponentName} = forwardRef((${props}) => (
        ${jsx}
      ));

      ${emptyLine}

      ${editedComponentName}.displayName = '${displayName}';

      ${emptyLine}

      export default ${editedComponentName};
    `;
  },
  titleProp: true,
  typescript: true,
};

module.exports = config;
