import {
  DiscountCalculatorHoverIcon,
  ExistingRequestHoverIcon,
  NewRequestHoverIcon,
  DiscountCalculatorIcon,
  ExistingRequestIcon,
  NewRequestIcon,
  DiscountCalculatorActiveIcon,
  NewRequestActiveIcon,
  ExistingRequestActiveIcon,
  ClassesSignupIcon,
  ShowPlacementIcon,
  CampSignupIcon,
  KindergartenSignupIcon,
  ClassesSignupHoverIcon,
  ShowPlacementHoverIcon,
  CampSignupHoverIcon,
  KindergartenSignupHoverIcon,
  ClassesSignupActiveIcon,
  ShowPlacementActiveIcon,
  CampSignupActiveIcon,
  KindergartenSignupActiveIcon,
  PlanningInfoIcon,
  ManagementCourseIcon,
  PlanningInfoHoverIcon,
  ManagementCourseHoverIcon,
  ManagementCourseActiveIcon,
  PlanningInfoActiveIcon,
  DebtClearanceIcon,
  DebtClearanceHoverIcon,
  DebtClearanceActiveIcon,
  PermitFileIcon,
  PermitFileHoverIcon,
  PermitFileActiveIcon,
  SeniorCenterIcon,
  SeniorCenterHoverIcon,
  SeniorCenterActiveIcon,
  GymFacilitiesIcon,
  GymFacilitiesHoverIcon,
  GymFacilitiesActiveIcon,
  BuySellAssetIcon,
  StartEndLeaseIcon,
  StartEndLeaseHoverIcon,
  IMBuyerIcon,
  IMBuyerHoverIcon,
  IMBuyerActiveIcon,
  BuySellAssetHoverIcon,
  BuySellAssetActiveIcon,
  StartEndLeaseActiveIcon,
  CommunalHomeIcon,
  CommunalHomeHoverIcon,
  CommunalHomeActiveIcon,
  WalletIcon,
  FilesFolderIcon,
  CardIdIcon,
  TimerIcon,
  WalletHoverIcon,
  FilesFolderHoverIcon,
  TimerHoverIcon,
  CardIdHoverIcon,
  WalletActiveIcon,
  FilesFolderActiveIcon,
  TimerActiveIcon,
  CardIdActiveIcon,
  WelfareIcon,
  ParkingIcon,
  ShieldIcon,
  ParkingHoverIcon,
  ShieldHoverIcon,
  WelfareHoverIcon,
  WelfareActiveIcon,
  ShieldActiveIcon,
  ParkingActiveIcon,
} from '@/assets';

export const ICONS_TABLE_KEYS = {
  discountCalculator: 'discountCalculator',
  existingRequest: 'existingRequest',
  newRequest: 'newRequest',
  classesSignup: 'classesSignup',
  showPlacement: 'showPlacement',
  campSignup: 'campSignup',
  kindergartenSignup: 'kindergartenSignup',
  planningInformation: 'planningInformation',
  managerialReserveCourse: 'managerialReserveCourse',
  noDebtsCertificate: 'noDebtsCertificate',
  permitInformationFile: 'permitInformationFile',
  renewalNoDebts: 'renewalNoDebts',
  seniorCitizensHome: 'seniorCitizensHome',
  fitnessFacilities: 'fitnessFacilities',
  buySellAsset: 'buySellAsset',
  IAmBuyer: 'IAmBuyer',
  startEndLease: 'startEndLease',
  communalHome: 'communalHome',
  cardId: 'cardId',
  timer: 'timer',
  filesFolder: 'filesFolder',
  wallet: 'wallet',
  welfare: 'welfare',
  shield: 'shield',
  parking: 'parking',
  planning: 'planning',
} as const;

export type IconType = keyof typeof ICONS_TABLE_KEYS;
export type IconState = 'default' | 'hover' | 'active';

export const ICONS_TABLE = {
  default: {
    [ICONS_TABLE_KEYS.discountCalculator]: DiscountCalculatorIcon,
    [ICONS_TABLE_KEYS.existingRequest]: ExistingRequestIcon,
    [ICONS_TABLE_KEYS.newRequest]: NewRequestIcon,
    [ICONS_TABLE_KEYS.classesSignup]: ClassesSignupIcon,
    [ICONS_TABLE_KEYS.showPlacement]: ShowPlacementIcon,
    [ICONS_TABLE_KEYS.campSignup]: CampSignupIcon,
    [ICONS_TABLE_KEYS.kindergartenSignup]: KindergartenSignupIcon,
    [ICONS_TABLE_KEYS.planningInformation]: PlanningInfoIcon,
    [ICONS_TABLE_KEYS.managerialReserveCourse]: ManagementCourseIcon,
    [ICONS_TABLE_KEYS.noDebtsCertificate]: DebtClearanceIcon,
    [ICONS_TABLE_KEYS.permitInformationFile]: PermitFileIcon,
    [ICONS_TABLE_KEYS.renewalNoDebts]: PermitFileIcon,
    [ICONS_TABLE_KEYS.seniorCitizensHome]: SeniorCenterIcon,
    [ICONS_TABLE_KEYS.fitnessFacilities]: GymFacilitiesIcon,
    [ICONS_TABLE_KEYS.buySellAsset]: BuySellAssetIcon,
    [ICONS_TABLE_KEYS.IAmBuyer]: IMBuyerIcon,
    [ICONS_TABLE_KEYS.startEndLease]: StartEndLeaseIcon,
    [ICONS_TABLE_KEYS.communalHome]: CommunalHomeIcon,
    [ICONS_TABLE_KEYS.cardId]: CardIdIcon,
    [ICONS_TABLE_KEYS.timer]: TimerIcon,
    [ICONS_TABLE_KEYS.filesFolder]: FilesFolderIcon,
    [ICONS_TABLE_KEYS.wallet]: WalletIcon,
    [ICONS_TABLE_KEYS.welfare]: WelfareIcon,
    [ICONS_TABLE_KEYS.shield]: ShieldIcon,
    [ICONS_TABLE_KEYS.parking]: ParkingIcon,
    [ICONS_TABLE_KEYS.planning]: PlanningInfoIcon,
  },
  hover: {
    [ICONS_TABLE_KEYS.discountCalculator]: DiscountCalculatorHoverIcon,
    [ICONS_TABLE_KEYS.existingRequest]: ExistingRequestHoverIcon,
    [ICONS_TABLE_KEYS.newRequest]: NewRequestHoverIcon,
    [ICONS_TABLE_KEYS.classesSignup]: ClassesSignupHoverIcon,
    [ICONS_TABLE_KEYS.showPlacement]: ShowPlacementHoverIcon,
    [ICONS_TABLE_KEYS.campSignup]: CampSignupHoverIcon,
    [ICONS_TABLE_KEYS.kindergartenSignup]: KindergartenSignupHoverIcon,
    [ICONS_TABLE_KEYS.planningInformation]: PlanningInfoHoverIcon,
    [ICONS_TABLE_KEYS.managerialReserveCourse]: ManagementCourseHoverIcon,
    [ICONS_TABLE_KEYS.noDebtsCertificate]: DebtClearanceHoverIcon,
    [ICONS_TABLE_KEYS.permitInformationFile]: PermitFileHoverIcon,
    [ICONS_TABLE_KEYS.renewalNoDebts]: PermitFileHoverIcon,
    [ICONS_TABLE_KEYS.seniorCitizensHome]: SeniorCenterHoverIcon,
    [ICONS_TABLE_KEYS.fitnessFacilities]: GymFacilitiesHoverIcon,
    [ICONS_TABLE_KEYS.buySellAsset]: BuySellAssetHoverIcon,
    [ICONS_TABLE_KEYS.IAmBuyer]: IMBuyerHoverIcon,
    [ICONS_TABLE_KEYS.startEndLease]: StartEndLeaseHoverIcon,
    [ICONS_TABLE_KEYS.communalHome]: CommunalHomeHoverIcon,
    [ICONS_TABLE_KEYS.cardId]: CardIdHoverIcon,
    [ICONS_TABLE_KEYS.timer]: TimerHoverIcon,
    [ICONS_TABLE_KEYS.filesFolder]: FilesFolderHoverIcon,
    [ICONS_TABLE_KEYS.wallet]: WalletHoverIcon,
    [ICONS_TABLE_KEYS.welfare]: WelfareHoverIcon,
    [ICONS_TABLE_KEYS.shield]: ShieldHoverIcon,
    [ICONS_TABLE_KEYS.parking]: ParkingHoverIcon,
    [ICONS_TABLE_KEYS.planning]: PlanningInfoHoverIcon,
  },
  active: {
    [ICONS_TABLE_KEYS.discountCalculator]: DiscountCalculatorActiveIcon,
    [ICONS_TABLE_KEYS.existingRequest]: ExistingRequestActiveIcon,
    [ICONS_TABLE_KEYS.newRequest]: NewRequestActiveIcon,
    [ICONS_TABLE_KEYS.classesSignup]: ClassesSignupActiveIcon,
    [ICONS_TABLE_KEYS.showPlacement]: ShowPlacementActiveIcon,
    [ICONS_TABLE_KEYS.campSignup]: CampSignupActiveIcon,
    [ICONS_TABLE_KEYS.kindergartenSignup]: KindergartenSignupActiveIcon,
    [ICONS_TABLE_KEYS.planningInformation]: PlanningInfoActiveIcon,
    [ICONS_TABLE_KEYS.managerialReserveCourse]: ManagementCourseActiveIcon,
    [ICONS_TABLE_KEYS.noDebtsCertificate]: DebtClearanceActiveIcon,
    [ICONS_TABLE_KEYS.permitInformationFile]: PermitFileActiveIcon,
    [ICONS_TABLE_KEYS.renewalNoDebts]: PermitFileActiveIcon,
    [ICONS_TABLE_KEYS.seniorCitizensHome]: SeniorCenterActiveIcon,
    [ICONS_TABLE_KEYS.fitnessFacilities]: GymFacilitiesActiveIcon,
    [ICONS_TABLE_KEYS.buySellAsset]: BuySellAssetActiveIcon,
    [ICONS_TABLE_KEYS.IAmBuyer]: IMBuyerActiveIcon,
    [ICONS_TABLE_KEYS.startEndLease]: StartEndLeaseActiveIcon,
    [ICONS_TABLE_KEYS.communalHome]: CommunalHomeActiveIcon,
    [ICONS_TABLE_KEYS.cardId]: CardIdActiveIcon,
    [ICONS_TABLE_KEYS.timer]: TimerActiveIcon,
    [ICONS_TABLE_KEYS.filesFolder]: FilesFolderActiveIcon,
    [ICONS_TABLE_KEYS.wallet]: WalletActiveIcon,
    [ICONS_TABLE_KEYS.welfare]: WelfareActiveIcon,
    [ICONS_TABLE_KEYS.shield]: ShieldActiveIcon,
    [ICONS_TABLE_KEYS.parking]: ParkingActiveIcon,
    [ICONS_TABLE_KEYS.planning]: PlanningInfoActiveIcon,
  },
};

// Helper function to get icon component by state and type
export const getIconComponent = (state: IconState, type: IconType) => {
  return ICONS_TABLE[state][type];
};
